### ISSUE TITLE
Self-closing tag should not have space

### ISSUE THREAD

**Issue by Tarnadas** [Schniz/render.rs#10]
Hi,

I'm currently trying to build a React renderer, which runs in WASM and I stumbled across a unit test, which tests self-closing tags.

Apparently it doesn't like the space before the self-closing tag, see [here](https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactServerRendering-test.js#L43).
I made a little more research and found [this](https://stackoverflow.com/questions/462741/space-before-closing-slash) StackOverflow question, which also leads to this W3C page:
https://www.w3.org/TR/xhtml1/#h-4.6

So I assume the space isn't required and should be omitted?

**Comment by Schniz** [comment]
You're right! haven't thought about it being unnecessary and a stylish opinion of mine 💃 
thanks!
