### ISSUE TITLE
Doesn't build with stable Rust

### ISSUE THREAD

**Issue by Ciantic** [Schniz/render.rs#44]
I think you may have intended this to work with stable Rust ([commit](https://github.com/render-rs/render.rs/commit/aa10a9d961573a4f05129f68575d2b9e0cacde31)) but it doesn't because `#![feature]` isn't in stable Rust:

```
cargo build
   Compiling render_macros v0.3.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\render_macros-0.3.1\src\lib.rs:1:1
  |
1 | #![feature(proc_macro_diagnostic)]
```

```
rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by wez** [comment]
There isn't a released version that builds with stable rust, however, you can point to master; I'm doing this in my `Cargo.toml`:

```toml
# We use `render` master as that doesn't require unstable rust
render = { git="https://github.com/render-rs/render.rs.git", rev="aa10a9d961573a4f05129f68575d2b9e0cacde31" }
```

**Comment by Ciantic** [comment]
Thanks, closing this.
